spring.application.name=CrudUsuario

spring.datasource.url=jdbc:postgresql://localhost:5432/crud_usuarios
spring.datasource.username=postgres
spring.datasource.password=19283746

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

